/*Created by Classic Cap Studios
Controls number and timing of waves, as well as
type of and number of enemies within those wave. Loops
through waves if all are completed.*/
using UnityEngine;
using System.Collections;

public class WaveSpawner : MonoBehaviour {

	//Establishes various states of the waves
	public enum SpawnState { SPAWNING, WAITING, COUNTING };

	//Allows us to edit values of instances from class type Wave within Unity
	[System.Serializable]

	//Defines what a "wave" is for our game
	public class Wave
	{
		public string name; //Wave name
		public Transform enemy; //Accepts and stores enemy transform to be spawned during wave
		public int count; //Number of enemies to spawn in wave.
		public float rate; // How fast to spawn enemies
	}

	public Wave[] waves;
	private int nextWave = 0;
	public int NextWave
	{
		get { return nextWave + 1; }
	}

	public Transform[] spawnPoints;

	public float timeBetweenWaves = 5f;
	private float waveCountdown;
	public float WaveCountdown
	{
		get { return waveCountdown; }
	}

	private float searchCountdown = 1f;

	private SpawnState state = SpawnState.COUNTING;

	//Retrieves spawn state
	public SpawnState State
	{
		get { return state; }
	}

	void Start()
	{
		//Checks to make sure there are spawn points
		if (spawnPoints.Length == 0)
		{
			Debug.LogError("No spawn points referenced.");
		}

		waveCountdown = timeBetweenWaves;
	}

	void Update()
	{
		//Checks that enemies in wave are destroyed before marking wave as complete
		if (state == SpawnState.WAITING)
		{
			if (!EnemyIsAlive())
			{
				WaveCompleted();
			}
			else
			{
				return;
			}
		}

		//Makes sure that a wave is not currently spawning
		//If false, then spawns next wave from index
		if (waveCountdown <= 0)
		{
			if (state != SpawnState.SPAWNING)
			{
				StartCoroutine( SpawnWave ( waves[nextWave] ) );
			}
		}
		else
		{
			waveCountdown -= Time.deltaTime;
		}
	}

	//Marks wave as complete
	void WaveCompleted()
	{
		Debug.Log("Wave Completed!");

		state = SpawnState.COUNTING;
		waveCountdown = timeBetweenWaves;

		if (nextWave + 1 > waves.Length - 1)
		{
			nextWave = 0;
			Debug.Log("ALL WAVES COMPLETE! Looping...");
		}
		else
		{
			nextWave++;
		}
	}

	//Check for alive enemies
	bool EnemyIsAlive()
	{
		searchCountdown -= Time.deltaTime;
		if (searchCountdown <= 0f)
		{
			searchCountdown = 1f;
			if (GameObject.FindGameObjectWithTag("Enemy") == null)
			{
				return false;
			}
		}
		return true;
	}

	//Spawns each wave successive wave
	IEnumerator SpawnWave(Wave _wave)
	{
		Debug.Log("Spawning Wave: " + _wave.name);
		state = SpawnState.SPAWNING;

		for (int i = 0; i < _wave.count; i++)
		{
			SpawnEnemy(_wave.enemy);
			yield return new WaitForSeconds( 1f/_wave.rate );
		}

		state = SpawnState.WAITING;

		yield break;
	}

	//Spawns enemies within each wave
	void SpawnEnemy(Transform _enemy)
	{
		Debug.Log("Spawning Enemy: " + _enemy.name);

		Transform _sp = spawnPoints[ Random.Range (0, spawnPoints.Length) ];
		Instantiate(_enemy, _sp.position, _sp.rotation);
	}

}
